### ISSUE TITLE
cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by unphased** [vanruesc/postprocessing#268]
### Description of the bug

Just trying to build tests/examples of the cloned repo on its own

```
03 00:28 ~/postprocessing ❯❯❯ rm -rf node_modules && npm i && npm run test

> core-js@2.6.12 postinstall /home/slu/postprocessing/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /home/slu/postprocessing/node_modules/eslint-watch/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> esbuild@0.8.39 postinstall /home/slu/postprocessing/node_modules/esbuild
> node install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 772 packages from 474 contributors and audited 775 packages in 7.226s

76 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (1 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

┌───────────────────────────────────────────────────────┐
│                npm update check failed                │
│          Try running with sudo or get access          │
│         to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/slu/.config │
└───────────────────────────────────────────────────────┘

> postprocessing@6.20.3 test /home/slu/postprocessing
> run-s lint build ava


> postprocessing@6.20.3 lint /home/slu/postprocessing
> eslint --ext .js --fix src demo/src


┌───────────────────────────────────────────────────────┐
│                npm update check failed                │
│          Try running with sudo or get access          │
│         to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/slu/.config │
└───────────────────────────────────────────────────────┘

> postprocessing@6.20.3 build /home/slu/postprocessing
> run-s build:*


> postprocessing@6.20.3 build:js /home/slu/postprocessing
> cross-env NODE_ENV=production ts-node-script esbuild

Error: Cannot find module 'fs/promises'
Require stack:
- /home/slu/postprocessing/node_modules/esbuild-plugin-glsl/dist/esbuild-plugin-glsl.cjs
- /home/slu/postprocessing/esbuild.config.ts
- /home/slu/postprocessing/esbuild.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/slu/postprocessing/node_modules/esbuild-plugin-glsl/dist/esbuild-plugin-glsl.cjs:7:562)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! postprocessing@6.20.3 build:js: `cross-env NODE_ENV=production ts-node-script esbuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the postprocessing@6.20.3 build:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/slu/.npm/_logs/2021-02-03T05_28_34_507Z-debug.log
ERROR: "build:js" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! postprocessing@6.20.3 build: `run-s build:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the postprocessing@6.20.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/slu/.npm/_logs/2021-02-03T05_28_34_548Z-debug.log
ERROR: "build" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! postprocessing@6.20.3 test: `run-s lint build ava`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the postprocessing@6.20.3 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/slu/.npm/_logs/2021-02-03T05_28_34_571Z-debug.log
```

I will look into why fs/promises is being looked for, and/or what it is.

**Comment by unphased** [comment]
I switched to node 14 and this ran fine. [This](https://stackoverflow.com/questions/64725249/fs-promises-api-in-typescript-not-compiling-in-javascript-correctly) hinted me that node 12 has problems with whatever dependency that tries to require/import promises with that path.

**Comment by vanruesc** [comment]
Thanks for pointing this out!

This was caused by one of the dev tools (`esbuild-plugin-glsl`) which is now fixed. It should now be possible to build `postprocessing` on `node≥0.10.18` after running `npm update`.
